operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        getAssets:
          function: actions/getAssets/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_STOCK_ENDPOINT: $AEM_STOCK_ENDPOINT
          annotations:
            require-adobe-auth: true
            final: true
        getOffers:
          function: actions/getOffers/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
            AEM_XF_DESTINATION_PATH: $AEM_XF_DESTINATION_PATH
            AEM_AUTHOR_HOST: $AEM_AUTHOR_HOST
          annotations:
            require-adobe-auth: true
            final: true
        getAudiences:
          function: actions/getAudiences/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        createOffer:
          function: actions/createOffer/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
            WORKFRONT_API_KEY: $WORKFRONT_API_KEY
            WORKFRONT_URL: $WORKFRONT_URL
          annotations:
            require-adobe-auth: true
            final: true
        createImage:
          function: actions/createImage/index.js
          web: 'yes'
          runtime: 'nodejs:16'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
            WORKFRONT_API_KEY: $WORKFRONT_API_KEY
            FIREFLY_CLIENT_ID: $FIREFLY_CLIENT_ID
            WORKFRONT_URL: $WORKFRONT_URL
          annotations:
            require-adobe-auth: true
            final: true
        generateCopy:
          function: actions/generateCopy/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            CHAT_GPT_KEY: $CHAT_GPT_KEY
          annotations:
            require-adobe-auth: true
            final: true
        generateCreative:
          function: actions/generateCreative/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            FIREFLY_CLIENT_ID: $FIREFLY_CLIENT_ID
            FIREFLY_CLIENT_SECRET: $FIREFLY_CLIENT_SECRET
          annotations:
            require-adobe-auth: true
            final: true
        copyXFandRename:
          function: actions/copyXFandRename/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
            AEM_XF_SOURCE_PATH: $AEM_XF_SOURCE_PATH
            AEM_XF_DESTINATION_PATH: $AEM_XF_DESTINATION_PATH
            AEM_XF_VARIATIONS_LIST: $AEM_XF_VARIATIONS_LIST
          annotations:
            require-adobe-auth: true
            final: true